### ISSUE TITLE
"Organizations" filter has old/unused affiliations

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/nccwsc-projects#103]
STR:

 - Search for "trees"
 - Under the "Filters", click on the All Organizations

You'll see that there's a number of old/outdated/incorrect organizations.  Should we remove this filter?

**Comment by hollychandler** [comment]
I think at one point the "organization" filter was pulling from PI affiliations (so it was a huge list of all the different orgs/universities/fed agencies etc. associated with our projects). Now, it looks like its just a list of the old CASC names. We need to either remove it or have it pull again from the affiliations (I could see this being a useful filter - if someone wanted to see projects specifically done by their university or something for example).

**Comment by brucecrevensten** [comment]
Per Holly -- just remove this filter.
