### ISSUE TITLE
Change color in project sidebar, test for 508

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/nccwsc-projects#123]
Use the color from the lightest stripe in the climate colors in the new logo.  Test for 508 compliance in terms of color contrast.

**Comment by BobTorgerson** [comment]
#66 contains the requested color

**Comment by carolynrosner** [comment]
Color #C8E1F5 (light blue from logo) passes all contrast tests, per https://webaim.org/resources/contrastchecker/
