### ISSUE TITLE
Can't get to document download or parent project from search results

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/nccwsc-projects#131]
STR:

- From the main page, search for Moose
- Scroll down to find "Effects of climate and plant phenology on recruitment of moose at the southern extent of their range".
- Click on it, you get a modal preview popup.

Expected: there's links to the parent project or directly to the document resource.
Actual: there's not!

**Comment by BobTorgerson** [comment]
While looking into this issue, it appears that we don't have enough data coming from the ScienceBase API to point this at a parent project in https://cascprojects.org but that we do have enough to at least point the modal to the ScienceBase article indicated from this publication entry. See below for the JSON that is returned for this exact document:

{
    "contacts": {
        "principal_investigators": [],
        "co_investigators": [],
        "authors": [
            {
                "name": "Kevin L. Monteith",
                "organization": null
            },
            {
                "name": "Robert W. Klaver",
                "organization": null
            },
            {
                "name": "Kent R. Hersey",
                "organization": null
            },
            {
                "name": "A. Andrew Holland",
                "organization": null
            },
            {
                "name": "Timothy P. Thomas",
                "organization": null
            },
            {
                "name": "Matthew J. Kauffman",
                "organization": null
            }
        ],
        "cooperator_partner": []
    },
    "contactSearchString": "Kevin L. Monteith Robert W. Klaver Kent R. Hersey A. Andrew Holland Timothy P. Thomas Matthew J. Kauffman",
    "organizations": [],
    "csc": {
        "name": "National CASC",
        "id": "5050cb0ee4b0be20bb30eac0"
    },
    "dates": {
        "start_date": null,
        "end_date": null,
        "publication_date": "2015",
        "created": "2016-06-09T04:15:51.016-06:00",
        "updated": "2022-05-16T09:52:59.417-06:00"
    },
    "relationships": null,
    "fiscal_year": null,
    "keywords": [
        "Oecologia"
    ],
    "topics": [],
    "subtopics": [],
    "hasMaps": false,
    "previewImage": null,
    "id": "575941d7e4b04f417c256809",
    "hasFolders": false,
    "parent_id": "4f4e4771e4b07f02db47e1e4",
    "status": "N/A",
    "summary": "Climate plays a fundamental role in limiting the range of a species, is a key factor in the dynamics of large herbivores, and is thought to be involved in declines of moose populations in recent decades. We examined effects of climate and growing ...",
    "body": "Climate plays a fundamental role in limiting the range of a species, is a key factor in the dynamics of large herbivores, and is thought to be involved in declines of moose populations in recent decades. We examined effects of climate and growing-season phenology on recruitment (8–9 months old) of young Shiras moose (Alces alces shirasi) over three decades, from 18 herds, across a large geographic area encompassing much of the southern extent of their range. Recruitment declined in 8 of 18 herds during 1980–2009, whereas others did not exhibit a temporal trend (none showed a positive trend). During those three decades, seasonal temperatures increased, spring–summer precipitation decreased, and spring occurred earlier, became shorter in duration, and green-up occurred faster. Recruitment was influenced negatively by warm temperatures during the year before young were born, but only for herds with declining recruitment. Dry spring–summers of the previous year and rapid rates of spring green-up in the year of birth had similar negative influences across declining and stable herds. Those patterns indicate both direct (year&nbsp;t&nbsp;) and delayed (year&nbsp;t−1) effects of weather and plant phenology on recruitment of young, which we hypothesize was mediated through effects on maternal nutritional condition. Suppressed nutrition could have been induced by (1) increased thermoregulatory costs associated with warming temperatures and (2) shortened duration of availability of high-quality forage in spring. Progressive reductions in net energetic gain for species that are sensitive to climate may continue to hamper individual fitness and population dynamics.",
    "title": "Effects of climate and plant phenology on recruitment of moose at the southern extent of their range",
    "types": [
        "Publication"
    ],
    "isCollapsed": true
}

I see two possible paths to solve this:

1. We can simply have the ScienceBase article shown as an anchor link such as: https://www.sciencebase.gov/catalog/item/575941d7e4b04f417c256809  which we would get from combining the main portion of the ScienceBase URL with the ID from the JSON above for all items that are not listed as projects.

2. We will need to request that the ScienceBase API be updated to include the information about what project each publication and other data product are associated with.

@hollychandler Do you have a recommendation on how you would like this solved?

**Comment by BobTorgerson** [comment]
This issue relates heavily to https://github.com/ua-snap/nccwsc-projects/issues/80 as well for how we want to solve this within the Project Explorer.

**Comment by BobTorgerson** [comment]
@hollychandler I wanted to bring this to your attention so we know how we should proceed with this issue.

**Comment by hollychandler** [comment]
Since the results are already pulling in the SB link, let's move forward with using that URL. Maybe as a phase 2 down the road, we can think about other options/changing the API but for now, I'd like to go ahead and use the SB link. THANKS! @BobTorgerson
