### ISSUE TITLE
Region map is way too big after loading the page in a narrow browser and then resizing

### ISSUE THREAD

**Issue by cstephen** [ua-snap/nccwsc-projects#145]
This affects Firefox, Chrome, Safari, and Edge (and likely all browsers).

STR:

- Make your browser window very narrow so that the "Search by topic" sidebar expands to the full width of browser.
- Reload the page.
- Resize your browser so that it is wider.

When the region map goes back to being side-by-side with the "Search by topic" sidebar, it is 2-3x too large and the browser adds horizontal scrolling to deal with it.

![image](https://user-images.githubusercontent.com/2566292/227368955-b7ad338a-800a-4d17-816a-88c6b2e2752d.png)

**Comment by brucecrevensten** [comment]
Need to retest / close @BobTorgerson
