### ISSUE TITLE
Main/Sub Project Links don't always work

### ISSUE THREAD

**Issue by hollychandler** [ua-snap/nccwsc-projects#146]
@brucecrevensten @BobTorgerson We have instances where we have a "main" project that lives in SB under the National CASC and then it has "sub-projects" that live under regional CASCs in SB. These show up on the project pages in PE as links to "Main projects" and to "Sub-Projects". Because of the way the URLs for PE project pages are built, these links don't always work. 

Example:
https://cascprojects.org/#/project/4f83509de4b0e84f60868124/6050e947d34eb1203124fe72

The first ID in that URL (4f83509de4b0e84f60868124) is for the North Central CASC folder b/c the referring project was from the NC page. So if you click on a "sub-project" on that page, it builds the URL with the NC ID....but the sub-projects don't live in the NC folder in SB so the link takes you to a blank page (e.g. https://cascprojects.org/#/project/4f83509de4b0e84f60868124/617996e1d34ea58c3c6fa1f0). 

<img width="893" alt="image" src="https://user-images.githubusercontent.com/85572743/230149126-9c72929f-71d3-47c2-9efe-b91689dc40e5.png">

**Comment by BobTorgerson** [comment]
@hollychandler Depending on the examples you can provide, if my solution doesn't work, I believe the simplest solution will be to have the ScienceBase team add in the CASC ID as part of the returned relationships. The code for the Project Explorer was built with the assumption that any subprojects would fall under the same CASC as the main project. Since this assumption is false in at least this case, the easiest path for us would be to have the ScienceBase API team add in the CASC ID as a returned field for each subproject that we can populate the URL from.

**Comment by BobTorgerson** [comment]
@hollychandler Thank you for sharing that main project! The solution that I found (workaround really) is that for any project that has National CASC as the "main project" and other CASCs under it for subprojects is to use the National CASC ID for the URL as it correctly configures the subproject URLs in the live site. For example, here was the URL for your first observed main project with failing subprojects:

https://cascprojects.org/#/project/4f83509de4b0e84f60868124/6050e947d34eb1203124fe72

However, if you change **4f83509de4b0e84f60868124** (North Central CASC ID) to **5050cb0ee4b0be20bb30eac0** (National CASC ID), the underlying subproject URLs are all correct and route to their subproject. You can see that in this URL below:

https://cascprojects.org/#/project/5050cb0ee4b0be20bb30eac0/6050e947d34eb1203124fe72

The reason that this is happening is that the API in ScienceBase that we query is returning multiple entries for the same item in ScienceBase, which I believe might be a bug. If you search for **Future of Fire: Towards a National Synthesis of Wildland Fire Under a Changing Climate** in the Advanced Search bar, you get a considerable amount more entries (20 to be exact) than you should be receiving. The reason for that is the API is returning the same item / project / subproject multiple times, once for the main project's CASC (National CASC in this case) and once for each subproject's CASC. You can see the returned JSON that is being decorated in the website from this URL query:

https://my.usgs.gov/casc-service/search?query=Future%20of%20Fire%3A%20Towards%20a%20National%20Synthesis%20of%20Wildland%20Fire%20Under%20a%20Changing%20Climate&topics=&subtopics=&organizations=

So without having the ScienceBase team fix that, we have very limited options on our front for how to fix this issue. However, there is the work around that I mentioned above that fixes this issue in the interim, you simply need to start at the main project that is listed under the National CASC which you can get to via the URL listed here: https://cascprojects.org/#/project/5050cb0ee4b0be20bb30eac0/6050e947d34eb1203124fe72 or by narrowing an Advanced Search for the main project down by using the CASC dropdown to select only the National CASC projects. 

Please let me know how you would like to proceed as this ticket is unfortunately unable to be closed by our team without help from the ScienceBase team. If the workaround is good enough for now, we can keep this ticket open but we won't hold up our push to launch production bug fixes for it any longer.

**Comment by hollychandler** [comment]
we can keep this ticket open while I think more about it / talk to the SB team and you can go ahead and push out other fixes. Thanks! @BobTorgerson

**Comment by hollychandler** [comment]
FYI - I'm trying to re-ignite this as a priority. I've contacted a SB dev and will let you know what happens on our end. Thanks!

**Comment by hollychandler** [comment]
@BobTorgerson OK I think the ScienceBase team has done a fix for this in the API. You should now find a "CASC Main ID" (or "project main ID"?) in the json for each project that will indicate which CASC it belongs to. I think they are thinking you'll be able to use that main ID to tell PE how to build the URL for the project so it no longer breaks....? Let me know if you see it and if this might work....Thanks!

**Comment by BobTorgerson** [comment]
@hollychandler Thanks for alerting me on this! As soon as I can, I will take a look to see if this will fix the issue on the front end. We are fully focused on wrapping up a different project currently, but I think I should be able to take a look at this in mid to late October. Thanks again!

**Comment by BobTorgerson** [comment]
Good afternoon @hollychandler,

I had the opportunity to take a look at this today and I'm not sure I see what has changed in the API that would help to generate these subproject URLs in the CASC Project Explorer. Here is the URL I am looking at that is the National CASC's main project for all of the other CASCs subprojects: https://my.usgs.gov/casc-service/projects/5050cb0ee4b0be20bb30eac0/6050e947d34eb1203124fe72

This can also be seen at: https://cascprojects.org/#/project/5050cb0ee4b0be20bb30eac0/6050e947d34eb1203124fe72

The returned JSON data from the API has the subprojects listed, but it does not contain the CASC ID for each subproject. It has the correct article ID, but without the CASC ID value, I can't create the correct URL in the cascprojects.org website. For example, if I try to use the CASC ID of the current project (i.e. the National CASC 5050cb0ee4b0be20bb30eac0), the URL in cascprojects.org with the subproject ID for the Southeast CASC (i.e. 61799748d34ea58c3c6fa1f5), I get a non-working project page: 

https://cascprojects.org/#/project/5050cb0ee4b0be20bb30eac0/61799748d34ea58c3c6fa1f5

You'll see that no affiliation is listed and the data is all missing in that above URL. However, if I have the Southeast CASC ID (i.e. 61799748d34ea58c3c6fa1f5), I get a working URL with all of the desired data:

https://cascprojects.org/#/project/4f8c6557e4b0546c0c397b4c/61799748d34ea58c3c6fa1f5

To generate this, I need each of the subprojects shown in the "relationships" section of the returned JSON to have the associated CASC ID so I can generate the correct URL. 

For example, the current API JSON looks like this for the Southeast CASC subproject:

"relationships": [
    {
      "url": "https://www.sciencebase.gov/catalog/item/61799748d34ea58c3c6fa1f5",
      "rel": "main project of",
      "relatedRel": "sub-project of",
      "title": "Future of Fire: Towards a National Synthesis of Wildland Fire Under a Changing Climate",
      "relatedTitle": "Development of an Early Warning System to Identify Changing Prescribed Burn Opportunities Across Southeast US Fire-Adapted Habitats",
      "id": "6050e947d34eb1203124fe72",
      "relatedId": "61799748d34ea58c3c6fa1f5",
      "annotation": null
    },

But what I really need for it to have is:

"relationships": [
    {
      "url": "https://www.sciencebase.gov/catalog/item/61799748d34ea58c3c6fa1f5",
      "rel": "main project of",
      "relatedRel": "sub-project of",
      "title": "Future of Fire: Towards a National Synthesis of Wildland Fire Under a Changing Climate",
      "relatedTitle": "Development of an Early Warning System to Identify Changing Prescribed Burn Opportunities Across Southeast US Fire-Adapted Habitats",
      "id": "6050e947d34eb1203124fe72",
      "relatedId": "61799748d34ea58c3c6fa1f5",
      **"cascId": "4f8c6557e4b0546c0c397b4c",**
      "annotation": null
    },
    
That will allow for me to generate the URL https://cascprojects.org/#/project/4f8c6557e4b0546c0c397b4c/61799748d34ea58c3c6fa1f5 from putting: https://cascprojects.org/#/project/<cascId>/<relatedId>

Let me know if this doesn't make sense, I'm happy to discuss with the API team what I need if this is unclear!

**Comment by hollychandler** [comment]
@BobTorgerson  I forwarded your message to our developer and they said they did another update to the JSON so you should see the needed field now. Can you check and let me know if it has what you need now? Thanks!
