### ISSUE TITLE
Home Page: SC 1.1.1 Images on the home page should have alternate text set

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#157]
As described in the review:

Images must have alternate text. Location(s):
− \<img _ngcontent-qdk-c27="" src="assets/images/usgs-200.png"\> 
− \<img _ngcontent-qdk-c27="" src="assets/images/akcasc-200.png"\> 
− \<img _ngcontent-qdk-c27="" src="assets/images/mwcasc-200.png"\> 
− \<img _ngcontent-qdk-c27="" src="assets/images/nccasc-200.png"\>
− \<img _ngcontent-qdk-c27="" src="assets/images/necasc-200.png"\>
− \<img _ngcontent-qdk-c27="" src="assets/images/nwcasc-200.png"\>
− \<img  _ngcontent-qdk-c27="" src="assets/images/picasc-200.png"\>
− \<img  _ngcontent-qdk-c27="" src="assets/images/sscasc-200.png"\>
− \<img _ngcontent-qdk-c27="" src="assets/images/secasc-200.png"\>
− \<img _ngcontent-qdk-c27="" src="assets/images/swcasc-200.png"\>
− \<img _ngcontent-qdk-c27="" src="assets/images/twitter.png" class="social-media-
icon"\>
− \<img _ngcontent-qdk-c27="" src="assets/images/instagram.png" class="social-media-
icon"\>

**Reasons flagged:**
− Element does not have an alt attribute.
− aria-label attribute does not exist or is empty.
− aria-labelledby attribute does not exist, references elements that do not exist or
references elements that are empty.
− Element has no title attribute.
− Element's default semantics were not overridden with role="none" or
role="presentation".

**Comment by hollychandler** [comment]
Approved!
