### ISSUE TITLE
Home Page: SC 4.1.2: Form elements must have labels.

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#162]
**Location(s):**
- \<input role="combobox" type="text" autocorrect="off" autocapitalize="none" autocomplete="a33b056c3d99" aria-expanded="false"\>
- \<input role="combobox" type="text" autocorrect="off" autocapitalize="none" autocomplete="a0c16b311d5f" aria-expanded="false"\>
- \<input role="combobox" type="text" autocorrect="off" autocapitalize="none" autocomplete="a2428a8c7015" aria-expanded="false"\>

**Reasons flagged:**
- Form element does not have an implicit (wrapped) <label>.
- Form element does not have an explicit <label>.
- aria-label attribute does not exist or is empty.
- aria-labelledby attribute does not exist, references elements that do not exist or
references elements that are empty.
- Element has no title attribute.
- Element has no placeholder attribute.
- Element's default semantics were not overridden with role="none" or
role="presentation".

**Comment by hollychandler** [comment]
Approved!

**Comment by BobTorgerson** [comment]
This was done in #217 when added to main.
