### ISSUE TITLE
Home Page: SC 4.1.2: Links must have discernible text.

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#163]
**Location(s):**
- \<a _ngcontent-qdk-c27="" href="https://twitter.com/usgs_climate?ref_src=twsrc%5Etfw"\>\<img _ngcontent-qdk- c27="" src="assets/images/twitter.png" class="social-media-icon"\>\</a\>
- \<a _ngcontent-qdk-c27="" href="https://www.instagram.com/usgs_climate/"\>\<img _ngcontent-qdk-c27="" src="assets/images/instagram.png" class="social-media- icon"\>\</a\>

**Reasons flagged:**
- Element does not have text that is visible to screen readers.
- aria-label attribute does not exist or is empty.
- aria-labelledby attribute does not exist, references elements that do not exist or
references elements that are empty.
- Element has no title attribute.
- Element's default semantics were not overridden with role="none" or
role="presentation".
- Element is in tab order and does not have accessible text.

**Comment by hollychandler** [comment]
Approved!

**Comment by BobTorgerson** [comment]
This was done in #217 when it was merged into main.
