### ISSUE TITLE
Minor issue: Improving clarity of sortable columns in topics and CASC pages

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#168]
**Problem:**

In the topics and CASC pages, we can see that the columns are sortable by panning over them, but that may not be clear to the end user. 

**Suggested solution:**

Make the sort by a drop down list of possible columns to sort by to make the functionality very obvious.

**Comment by hollychandler** [comment]
Needs additional thought

**Comment by BobTorgerson** [comment]
We will have the year column display the arrow indicating the ability to be sorted by default.
