### ISSUE TITLE
New color codes for CASCs to replace colors on map

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#169]
Holly will get us a list of color codes that each of the CASCs will be changing to and she would like those CASC areas on the map to match those colors.

**Comment by hollychandler** [comment]
@BobTorgerson New color codes for the project explorer home page map! Thanks!

Alaska: #6DAD77
Pacific Islands: #EE7D59
Northwest: #095197
Southwest: #AA4342
North Central: #008057
South Central: #EFAE50
Midwest: #5478BF
Northeast: #906391
Southeast: #179FC0

**Comment by BobTorgerson** [comment]
@hollychandler Thanks! I'll pass this along to our design expert for recreating the map with these color codes.

**Comment by BobTorgerson** [comment]
![CASC map with NCASC new colors](https://github.com/ua-snap/nccwsc-projects/assets/563260/739f96a9-fd0c-4b65-9c44-456dff973e86)
