### ISSUE TITLE
Modify tag line in header of site

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#56]
It was suggested that we modify the tag line in the header of the site from "Discover regional climate data" to "Discover regional climate change impacts". They may have a different tag line they all agree on when we receive the full feedback.

**Comment by hollychandler** [comment]
CASC team still needs to discuss and will provide updated tagline in coming weeks (TBD)

**Comment by brucecrevensten** [comment]
I think I heard that we're OK with "Discover regional climate science", @hollychandler does this seem accurate to you?  (It's what's currently on the dev instance of the tool).

**Comment by hollychandler** [comment]
yes - you can leave this as sis for now. thanks!

**Comment by carolynrosner** [comment]
The only thing about leaving the white bar/header there is, it explains what CASC stands for right away. Otherwise, one doesn't really know. So I'd suggest keeping that white header bar up there.

**Comment by hollychandler** [comment]
In that case, would it be possible to have it be a dark blue bar with white text at the very top instead of the white bar?

**Comment by carolynrosner** [comment]
Yes, that could work. Match color of footer, and maybe a thin white border between the top bar and the header bar, if that makes sense. Really, this tool looks fabulous and ready to launch! :-)
