### ISSUE TITLE
National CASC is missing from explore by regions map

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#57]
The National CASC is missing in the regions map, we need to add that and update the area mapping.

**Comment by hollychandler** [comment]
We were thinking we could work National CASC in to home page map by changing the title of this section to "Search by Center" (instead of "Search by Region") and then we could add a dot/star on the map at Reston, VA with a button for National CASC. Let us know what you think about that. We're open to different ideas also

**Comment by carolynrosner** [comment]
Here's a map with the NCASC added - thoughts?

<img width="1029" alt="Screen Shot 2022-01-31 at 3 23 34 PM" src="https://user-images.githubusercontent.com/5123589/151889397-98695ea6-a50f-4b5d-91e5-d214e766d11c.png">

**Comment by hollychandler** [comment]
The yellow throws me off a little bit - I wonder if making that label look the same as the other labels (so there's a visual clue that that button functions the same way) would be better...what do you think?

**Comment by carolynrosner** [comment]
Yeah, it is kind of Too Much -- here it is with white. 
<img width="1031" alt="Screen Shot 2022-01-31 at 3 31 56 PM" src="https://user-images.githubusercontent.com/5123589/151890187-aa201fa3-9a26-4c72-9ec0-5c4356e9dc17.png">

**Comment by hollychandler** [comment]
I like that! thanks!

**Comment by carolynrosner** [comment]
Great!

**Comment by carolynrosner** [comment]
Cleaned-up CASC map (SVG) with NCASC added, borders adjusted on some states, and outlines added to PR, AK, HI.

![CASC map with NCASC](https://user-images.githubusercontent.com/5123589/155582635-ba8fb202-5b93-42d5-9239-f654128c1d35.svg)
