### ISSUE TITLE
Change FY to just Year in all tables

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#60]
We were told that using just Year rather than FY for the tables would be clear, we will make that change in all of the tables that have that as a header.

**Comment by hollychandler** [comment]
Also make the change to the Filter that shows up on left side of list pages
<img width="773" alt="image" src="https://user-images.githubusercontent.com/85572743/151888550-f0d7c197-05cb-4c20-b6dc-b2d69a37cb97.png">

**Comment by hollychandler** [comment]
Also Advanced search filter 
<img width="449" alt="image" src="https://user-images.githubusercontent.com/85572743/151888726-774f43c9-2281-4e52-b0dd-461820b70823.png">
