### ISSUE TITLE
Remove the "CASC" from the side bar under topics for each of the associated CASCs

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#62]
For example, this would mean changing "Alaska CASC" to just "Alaska".

**Comment by BobTorgerson** [comment]
This should be done on the API and things will work if the CASC from the backend is removed.

**Comment by hollychandler** [comment]
Hey @BobTorgerson, just to clarify - you're saying this would need to be done from our end / SB end right? There are several different places on the ScienceBase record where we identify the CASC ("Community" name, Organization tag, Funding Agency contact field, etc.) - can you tell which specific field the PE side bar is pulling from? Thanks!

**Comment by BobTorgerson** [comment]
@hollychandler I've found a fairly simple way to have this work on our end without needing to modify all of the Science Base pages with modified CASC names. While in most cases, the API should be the authoritative source for naming convention and truth, in this case, we are simply removing the same text from each value so can easily be done on our end without the need for a lot of additional work on your end or the SB team.
