### ISSUE TITLE
Add USGS logo in footer of site

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#64]
This was suggested as a way of adding the USGS logo on the site.

**Comment by hollychandler** [comment]
![USGS-white-transparent](https://user-images.githubusercontent.com/85572743/151883463-4b097ad1-1951-4717-8a6e-7676501458ed.png)

**Comment by carolynrosner** [comment]
Thanks! Not sure what file format the above logo is, but I suggest using an SVG if possible -- it'll be crisper than the PNG that I assume the previously uploaded file is.

**Comment by hollychandler** [comment]
k, let me try and track an SVG file down. we were also thinking it'd be nice to also include the nine regional CASC logos in the footer bar. Do you think that would be doable? if so, I can get you those files as well.

**Comment by carolynrosner** [comment]
I have an SVG of the USGS logo, so no worries there. Do you have all of the regional logos handy, by any chance? Normally we try to discourage a zillion logos in footers, but in this case it seems appropriate. Ideally it'd be nice to get vector files of all of those logos, but failing that, PNG work.

**Comment by hollychandler** [comment]
I think we have PNGs of all of them on hand. If you think SVG would make a huge difference in quality, I would need to contact each casc to ask for them, and I'm not totally sure they'd have them. Let me know if you think its significant enough to try to get them!

**Comment by carolynrosner** [comment]
Probably PNG is fine. If they happen to also have Adobe Illustrator versions as well, I'd love to have those too, if possible. I can make SVGs from those if I want to. AK CASC has a new logo by the way!  :-)  Please send what you have readily available, let's start with that and see how it looks. Thank you!

**Comment by carolynrosner** [comment]
The problem I have found with adding the CASC logos is that not all of them have logos (e.g. Southeast CASC, Northwest CASC). Midwest CASC website can't even be reached to see if they have a logo. Would you be OK? with listing the CASCS in the footer, with just type, and not logos except for the USGS logo?

**Comment by carolynrosner** [comment]
Holly -- what about this approach? A bit more description of the CASCs in the 'fat footer', with CASC names as links to their sites. Because of what I mentioned above, actual CASC logos won't work very well, but 'buttons' with colors corresponding to the map above could work. Or, if too much, just use underlined white text for the links.

<img width="1591" alt="Screen Shot 2022-02-01 at 1 47 05 PM" src="https://user-images.githubusercontent.com/5123589/152059187-96a05e6c-d062-47e8-a8df-9909614f18fa.png">

**Comment by hollychandler** [comment]
every CASC, except for MW, does have a logo (I think MW will probably develop one, but they are just getting started) and we have files for all of them (most are png I believe). it might be worth waiting until MW gets one to put them on PE, just so we have them all. I still like the idea of at least trying to get the logos in the footer. I like how NW CASC displays their partner logos across the bottom of their page: https://nwcasc.uw.edu/ maybe we could do something like that except as part of our footer? I'll try and get you the logos this morning!

**Comment by hollychandler** [comment]
[CASC logos.zip](https://github.com/ua-snap/nccwsc-projects/files/7988231/CASC.logos.zip)

**Comment by carolynrosner** [comment]
Thanks for the logos, I'll share with AK CASC folks here too. By the way, AK CASC has a new logo, that I designed -- attached here! We have already rolled it out, so please feel free to use in any future communications products you create.
[AK CASC_logos_all.zip](https://github.com/ua-snap/nccwsc-projects/files/7988557/AK.CASC_logos_all.zip)

**Comment by carolynrosner** [comment]
Here's a layout with a logo grid. We could do the blue box text part for now, but could wait on the grid until MW CASC gets an actual logo. Or, if you're OK with the "placeholder logo" (UMinn is their host U) we could use this layout? If you don't want to include the placeholder logo, we recommend doing no logos at all until they have an official one. 

<img width="1060" alt="Screen Shot 2022-02-02 at 10 07 17 AM" src="https://user-images.githubusercontent.com/5123589/152214365-b3367e78-3be8-444a-8cee-e74551df23f4.png">

**Comment by hollychandler** [comment]
I like the new AK logo - very cool! and I like the way the logos look laid out like that. I think it might be better to put USGS first though (top row, far left). I'll check on what MW prefers and what the status of their logo is. thanks!

**Comment by carolynrosner** [comment]
Thanks! We went through about 1000000000 iterations on that design, but it was worth it! I put USGS in the middle, top row, for better balance -- it's such a heavy logo that having it on the left kind of throws everything off. Do MW CASC even have a website yet? I haven't been able to find it.

**Comment by hollychandler** [comment]
No, MW doesn't have a logo yet. They are working on hiring a comms person now

**Comment by hollychandler** [comment]
@BobTorgerson I think it might be better if we put all the logos inside the footer bar so its clearer that the logos are for the entire site.  Particularly on an individual project page (e.g. http://dev.cascprojects.org/#/project/4f83509de4b0e84f60868124/6009c274d34e162231fb2335) , it almost looks like the logos represent who is involved in the project, rather than being a part of the footer for the whole site
