### ISSUE TITLE
Pale blue or gray background color behind right sidebar of project

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/nccwsc-projects#66]
To make this section stand out more, it was suggested that we add a splash of pale color to differentiate those sections better.

**Comment by BobTorgerson** [comment]
Change to #C8E1F5

**Comment by carolynrosner** [comment]
Color #C8E1F5 (light blue from logo) PASSES contrast tests with black text.
Color #186DC7 (link color)  FAILS contrast checks.

Suggest lightening the background to #E6F1F9, this will pass contrast tests for both regular text and links.

source:  https://webaim.org/resources/contrastchecker/
