### ISSUE TITLE
Add new logo/icon in header bar

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#71]
CASC team will provide new art.

**Comment by BobTorgerson** [comment]
@hollychandler Do you have a new logo you would like to use in the header bar?

**Comment by hollychandler** [comment]
We are waiting on the logo to be finalized - should have that to you soon. 

For the tagline, we will leave it as is for now: "Discover regional climate science."

**Comment by hollychandler** [comment]
@BobTorgerson can you also change the logo that shows up in the browser tab to match this new icon? 
<img width="333" alt="image" src="https://user-images.githubusercontent.com/85572743/168131063-7ccce60d-f349-4623-a0f4-72b7ffbf524b.png">

**Comment by BobTorgerson** [comment]
@hollychandler Yes, this has been changed and we will push it to the development site later today

**Comment by hollychandler** [comment]
think this is done and can be closed?
