### ISSUE TITLE
Change header bar background image

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#73]
CASC team will provide new background image.

**Comment by BobTorgerson** [comment]
@hollychandler Do you have a new background image for the header bar that you would prefer?

**Comment by hollychandler** [comment]
See attached for the image we'd like to use. NOTE: this will need to be cropped. We weren't sure what dimensions you needed so we sent the full image. Also attached is a mockup so you can see what portion of the photo we are thinking would be good. Let me know if you need a different size/format. Thanks
![PE_banner_image](https://user-images.githubusercontent.com/85572743/166721035-bdf09d6e-a616-47a9-9201-7c641caa5d74.png)
![PE_banner_mockup](https://user-images.githubusercontent.com/85572743/166721044-61e56aff-0ce7-4780-b015-d7872c525654.jpg)
!
