### ISSUE TITLE
Add 'boilerplate' statement at bottom of home page, above footer

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#76]
CASC team will provide text.

**Comment by BobTorgerson** [comment]
@hollychandler Do you have "boilerplate" you would like put at the bottom of the home page?

**Comment by hollychandler** [comment]
Here's the text. Thanks!

The Climate Adaptation Science Centers (CASCs) deliver science to help fish, wildlife, water, land, and people adapt to a changing climate. The CASCs fund projects generating research, data sets, and tools to help natural and cultural resource managers protect natural places & local communities in a changing climate. The CASC network is comprised of the National CASC and nine regional CASCs, covering the continental U.S., Alaska, Hawai'i, the U.S. Affiliated Pacific Islands, and the U.S. Caribbean. [Learn more about the CASCs](https://www.usgs.gov/programs/climate-adaptation-science-centers).

**Comment by hollychandler** [comment]
@BobTorgerson also, it might be nice to have all of the text in the footer be white and I wonder if we could use cleaner, white social media icons (similar to the footer on the AK CASC website: https://akcasc.org/) ?
