### ISSUE TITLE
Display "Type" as colored label at top of search result box, below title of result

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#79]
Type can = Project, Data, or Publication for a search result. We want to make it more clear which type of result you are seeing. If this needs clarification, Holly can provide a quick mock up

**Comment by BobTorgerson** [comment]
@hollychandler Would you mind doing a quick mockup to show how you would like this to work?

**Comment by hollychandler** [comment]
yes! will get to you asap

**Comment by hollychandler** [comment]
@BobTorgerson  see attached ppt, let me know if you need clarification on anything!
[PE search results - TYPE.pptx](https://github.com/ua-snap/nccwsc-projects/files/8584940/PE.search.results.-.TYPE.pptx)

**Comment by BobTorgerson** [comment]
Great! This helps me to understand where those should go and as what color, I'll get on this today!

**Comment by hollychandler** [comment]
I think there are some other "types" that show up occasionally like "map" and "website", but after some quick searches, they are not pulling meaningful search results and seem to be based on arbitrary criteria. I think moving forward with only 4 "types" makes sense: Project, Publication, Data, and Other Product. does that make sense?

**Comment by hollychandler** [comment]
Also note for products where the search results open up in a pop up window, the new Type label should also show up in the pop up. example: 
![image](https://user-images.githubusercontent.com/85572743/165844700-8c84ef77-02b5-47cf-90cc-9692ba782304.png)
