### ISSUE TITLE
Add links to data/pub search results (TBD)

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#80]
Advanced search results for data and publications currently open a pop up box, but there's no link to the actual product. I'm not totally sure what is best to do here (for pubs, do we link directly to the pub URL & to the associated project page? for data, do we link to Sciencebase?) CASC Team needs to think about this a little bit more (TBD)

**Comment by hollychandler** [comment]
Here's what I'm thinking for this solution. Is this possible? Can you pull in the links and associated project into the search results?
[PE search results - Products URLs.pptx](https://github.com/ua-snap/nccwsc-projects/files/8586666/PE.search.results.-.Products.URLs.pptx)

**Comment by hollychandler** [comment]
so it looks like products/pubs already exist as standalone pages in PE (e.g. https://cascprojects.org/#/project/4f83509de4b0e84f60868124/6321feb7d34e71c6d67ab4ab) - we could just link the search results to those pages but we'd need to build the code out for those pages a little bit to include links, etc.
