### ISSUE TITLE
Time-out issue with advanced search

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#81]
When user searches for something generic like "climate" on the home page advanced search, the site times out and they get a "page not responsive" error. Not sure if its just an issue with the beta site? Maybe it would also help to add a spinning wheel loader like what we have on prod when results are loading.

**Comment by hollychandler** [comment]
I just tested this one again. I searched climate. the spinning wheel works great. but it does still seem to be timing out. (just fyi - doing some testing!)

**Comment by BobTorgerson** [comment]
With the changes to the backend API at ScienceBase, this no longer is an issue in my browser. It does take a long time to return because of the ubiquity of climate as a keyword in the projects, but it does return before timing out.
