### ISSUE TITLE
Fix strange anchor link behavior on click

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#82]
Bug? When clicking on a  topic or sub-topic from a project page, it jumps you to the very bottom of the topic/sub-topic list page

**Comment by BobTorgerson** [comment]
I'm not sure that this is still a thing with the updates made thus far. I'm going to keep this open, but after some more testing, I'll consider closing this as resolved.

**Comment by hollychandler** [comment]
this looks fixed to me. I think it can be closed.
