### ISSUE TITLE
Fix mysterious disappearing topics

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#83]
If we have a project tagged with a Topic but no sub-topics in Sciencebase, the Topics don't show up on Project Explorer

**Comment by BobTorgerson** [comment]
Please provide an example so that I can verify this is fixed. I can see code that should prevent this from being the case.

**Comment by BobTorgerson** [comment]
@hollychandler For this particular Science Base item, I do see the Science Themes but from the USGS cache service API I see this for that item: 

https://my.usgs.gov/casc-service/search?query=Mapping%20Connections%20across%20Ecosystems%20in%20the%20Northeast%20to%20Inform%20Climate%20Refugia%20Networks&topics=&subtopics=&organizations=

Note that this particular item does not contain the two fields that we are looking for in the CASC Project Explorer which are "topics" and "subtopics". I can't speak to how those are generated in Science Base, but it appears this particular item does not have those listed. 

In contradiction, here is a Science Base item along with its cache reference correctly showing the topics and subtopics:

**CASC Project Explorer**
http://dev.cascprojects.org/#/project/4f83509de4b0e84f60868124/60491adad34eb120311ac1ef

**Science Base item**
https://www.sciencebase.gov/catalog/item/60491adad34eb120311ac1ef

**API cache entry for Science Base item**
https://my.usgs.gov/casc-service/search?query=A%20Climate%20Vulnerability%20Assessment%20Framework%20for%20Data&topics=&subtopics=&organizations=North%20Central%20CASC

If you take a look at that Science Base item alongside the metadata associated with the one that doesn't work, there must be something missing for the topics / subtopics to not show up that should be rectified. When it is changed, that topic  + subtopics will show up for that item in the CASC Project Explorer too.

**Comment by hollychandler** [comment]
Weird - I have the topics added in exactly the same way for both records in ScienceBase so I don't understand why it would show up in the API entry for one and not the other. I'll put in a ticket with the SB team to have them take a look.

**Comment by hollychandler** [comment]
This has been fixed by the ScienceBase team so that Science Topics will now show up even if there are no science sub-topics selected in Sciencebase. 

NOTE: Can we fix the front end so that the label "Science subtopics" doesn't show up unless there are science subtopics that exist? or is this another issue with the API? 
example: https://cascprojects.org/#/project/4f8c648de4b0546c0c397b43/61084ec3d34ef8d70565c020
<img width="884" alt="image" src="https://user-images.githubusercontent.com/85572743/178356950-13f9944c-80ac-4fd5-b433-b8555b176438.png">

**Comment by hollychandler** [comment]
This original issue was resolved and I'm not sure my previous comment from July is still necessary. Let's hold off on that extra step and can close this ticket now. @brucecrevensten @BobTorgerson thanks!
