### ISSUE TITLE
Multi-CASC projects show up separately in advanced search

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#86]
Holly: we have some projects that are multi-casc. if you search for one in advanced search (e.g. Synthesizing Climate Change Impacts on Wildlife Health and Identifying Adaptation Strategies) it shows up in the results 9 times. each result is identical except for the CASC. technically in sciencebase the project only exists as 1 record, we just have it linked to the different CASCs. 

ideally in project explorer, we could have it show up as the same - 1 record in search results and on the topic list pages. But we'd still need it to show up on each of the casc region pages. not sure if this is possible. let me know if you need clarification...

**Comment by BobTorgerson** [comment]
This is something that would need to be fixed on the API side which is managed by Dell and his team. If you go to the cache you will see that 9 results are returned, and we are just displaying what is coming back from the API: https://my.usgs.gov/casc-service/search?query=Synthesizing%20Climate%20Change%20Impacts%20on%20Wildlife%20Health%20and%20Identifying%20Adaptation%20Strategies&topics=&subtopics=&organizations=

We don't want to be in the business of modifying results coming back from the API, you can get into trouble quickly doing so. The logic should reside in the API and we simply make the data look good.

**Comment by hollychandler** [comment]
ticket submitted to SB team

**Comment by BobTorgerson** [comment]
This is a two year old ticket with no traction from the SB team, we are closing it as no longer valid.
