### ISSUE TITLE
Open Contact Us link in new tab?

### ISSUE THREAD

**Issue by carolynrosner** [ua-snap/nccwsc-projects#88]
I had a tester report that when your default email client is set to Gmail, the Contact Us link at the bottom of the page opens a gmail window in the same tab. When she closed out of the email window, the entire PE tab closed too and she had to restart. I use Microsoft desktop app, at the email box opens in a new window which works well. This may be an issue for web-based email systems. Could we have those open in a new tab (if possible)?

**Comment by carolynrosner** [comment]
We could avoid this by just spelling out the email, and not having an email client open anything. A new tab does not seem like expected or desirable behavior.

**Comment by BobTorgerson** [comment]
@carolynrosner Do we have an idea what we would like to do with this issue? Do we want to spell out the email address or just leave it the way it is? In the design image for this issue: https://github.com/ua-snap/nccwsc-projects/issues/64 it still has the Contact Us as an anchor link which will open an email.
